name: getimages
on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    tags: 'v*'
  watch:
    types: [started]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        curl -fsSL https://get.docker.com -o get-docker.sh
        sudo sh get-docker.sh
        sudo usermod -aG docker ${USER}
        sudo docker pull xhofe/alist
        docker save -o alsit.tar  xhofe/alist:latest
        # sudo docker pull youshandefeiyang/allinone
        # docker save -o allinone.tar  oushandefeiyang/allinone:latest
        # sudo docker pull 6053537/portainer-ce
        # docker save -o portainer-ce.tar  6053537/portainer-ce:latest
    #     sudo apt-get update
    #     sudo apt-get -y install zip unzip 
    #     sudo python -m pip install --upgrade pip
    #     if [ -f requirements.txt ]; then sudo pip install -r requirements.txt; fi
    - name: run script
      run: |
        # fetch new ip content and update readme file
        # sudo python check_share_id.py
        # rm -rf *.tar
        # sudo python docker_pull.py xhofe/alist
        # sudo python docker_pull.py p3terx/aria2-pro 
        # tar -czvf data.tar.gz plugin.video.aliyunshare/
    - name: commit
      id: commit
      run: |
        git config --global user.email 2486251172@qq.com
        git config --global user.name hbyhzx
        git add .
        git commit -m "更新阿里分享链接 "
        git push
      continue-on-error: true
    - name: Check on failures
      if: steps.commit.outputs.status == 'failure'
      run: exit 1

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}

    # - name: Mirror the Github organization repos to Gitee.
    #   uses: Yikun/hub-mirror-action@master
    #   with:
    #     src: github/adai100
    #     dst: gitee/hbyhzx
    #     dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
    #     dst_token: ${{ secrets.GITEE_TOKEN }}
    #     force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
    #     static_list: "adai100.github.io" 
    #     static_list: "dockerimage" 

    - name: Mirror the Github organization repos to Gitee.
      uses: Yikun/hub-mirror-action@master
      with:
        src: github/adai100
        dst: gitee/hbyhzx
        dst_key: ${{ secrets.GITEE_PRIVATE_KEY }}
        dst_token: ${{ secrets.GITEE_TOKEN }}
        force_update: true  # 启用后，强制同步，即强制覆盖目的端仓库
        static_list: "dockerimage" 